# Generated by Django 4.2.20 on 2025-04-03 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_fbuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='fbuser',
            name='bio',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
