# Generated by Django 4.2.20 on 2025-04-09 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_post_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="likes",
            name="created_at",
            field=models.DateField(auto_now=True),
        ),
    ]
