# Generated by Django 4.2.20 on 2025-04-03 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_fbuser_date_joined_fbuser_is_active_fbuser_is_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fbuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
