# Generated by Django 4.2.20 on 2025-04-04 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
