# Generated by Django 4.2.20 on 2025-04-16 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_fbuser_bio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fbuser",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                default="/static/images/Default_pfp.jpg",
                null=True,
                upload_to="images/",
            ),
        ),
    ]
