# Generated by Django 4.2.20 on 2025-04-21 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_fbuser_cover_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fbuser",
            name="email",
            field=models.CharField(max_length=254, unique=True),
        ),
    ]
