# Generated by Django 4.2.20 on 2025-04-21 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_alter_fbuser_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="fbuser",
            name="username",
            field=models.CharField(default="div", max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="fbuser",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
