# Generated by Django 4.2.20 on 2025-05-27 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0018_alter_fbuser_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="fbuser",
            name="diamonds",
            field=models.IntegerField(default=0),
        ),
    ]
