# Generated by Django 4.2.20 on 2025-06-04 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0019_fbuser_diamonds"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fbuser",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
