# Generated by Django 4.2.20 on 2025-06-04 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0020_alter_fbuser_profile_picture"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fbuser",
            old_name="diamonds",
            new_name="stars",
        ),
    ]
