# Generated by Django 4.2.20 on 2025-04-14 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_delete_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fbuser",
            name="bio",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
