# Generated by Django 4.2.20 on 2025-04-16 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_alter_fbuser_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="fbuser",
            name="cover_photo",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
