# Generated by Django 4.2.20 on 2025-04-21 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_remove_fbuser_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="fbuser",
            name="username",
            field=models.CharField(default="username", max_length=254, unique=True),
        ),
    ]
