# Generated by Django 4.2.20 on 2025-05-01 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0017_alter_fbuser_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fbuser",
            name="profile_picture",
            field=models.ImageField(
                blank=True, default=None, null=True, upload_to="images/"
            ),
        ),
    ]
