# Generated by Django 4.2.20 on 2025-04-10 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0005_rename_likes_like"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="likes",
            field=models.IntegerField(default=0),
        ),
    ]
