# Generated by Django 4.2.20 on 2025-04-10 11:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("posts", "0007_remove_post_likes_delete_like_post_likes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="likes",
            field=models.ManyToManyField(
                null=True, related_name="likes", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
